const mimeTypes = {
  json: 'application/json', pdf: 'application/pdf', png: 'image/png', jpg: 'image/jpeg',
  jpeg: 'image/jpeg', gif: 'image/gif', webp: 'image/webp', avif: 'image/avif',
  mp4: 'video/mp4', webm: 'video/webm', mp3: 'audio/mpeg', wav: 'audio/wav',
  ogg: 'audio/ogg', txt: 'text/plain', csv: 'text/csv', tsv: 'text/tab-separated-values',
};

export function formatJson(value) {
  if (typeof value !== 'string') return JSON.stringify(value, null, 2);
  try { return JSON.stringify(JSON.parse(value), null, 2); } catch { return value; }
}

export function previewType(name, mime = '') {
  const extension = name.split('.').pop().toLowerCase();
  const type = mimeTypes[extension] || mime.split(';')[0];
  if (type === 'application/json') return 'json';
  if (['image/png', 'image/jpeg', 'image/gif', 'image/webp', 'image/avif'].includes(type)) return 'image';
  if (type === 'application/pdf') return 'pdf';
  if (['video/mp4', 'video/webm'].includes(type)) return 'video';
  if (['audio/mpeg', 'audio/wav', 'audio/ogg'].includes(type)) return 'audio';
  if (['text/plain', 'text/csv', 'text/tab-separated-values'].includes(type)) return 'text';
  return 'download';
}

// Reports generated by buildExperimentSubmission use uncompressed ZIP entries.
// Read their central directory rather than guessing boundaries from file bytes.
export async function readEvidenceFiles(blob, name = 'minh-chung') {
  const bytes = new Uint8Array(await blob.arrayBuffer());
  const view = new DataView(bytes.buffer);
  if (bytes.length < 4 || view.getUint32(0, true) !== 0x04034b50) {
    return [{ name, blob: new Blob([bytes], { type: mimeTypes[name.split('.').pop().toLowerCase()] || blob.type }) }];
  }
  const invalid = () => { throw new Error('Tệp ZIP không hợp lệ hoặc bị hỏng.'); };
  if (bytes.length < 22) invalid();
  let end = bytes.length - 22;
  while (end >= Math.max(0, bytes.length - 65557)) {
    if (view.getUint32(end, true) === 0x06054b50 && end + 22 + view.getUint16(end + 20, true) === bytes.length) break;
    end -= 1;
  }
  if (end < Math.max(0, bytes.length - 65557)) invalid();
  if (view.getUint16(end + 4, true) || view.getUint16(end + 6, true)) invalid();
  const count = view.getUint16(end + 10, true);
  let offset = view.getUint32(end + 16, true);
  const directoryEnd = offset + view.getUint32(end + 12, true);
  if (directoryEnd > end || count > 100) invalid();
  const files = [];
  for (let index = 0; index < count; index += 1) {
    if (offset + 46 > directoryEnd || view.getUint32(offset, true) !== 0x02014b50) invalid();
    const flags = view.getUint16(offset + 8, true);
    const method = view.getUint16(offset + 10, true);
    const size = view.getUint32(offset + 20, true);
    const nameLength = view.getUint16(offset + 28, true);
    const next = offset + 46 + nameLength + view.getUint16(offset + 30, true) + view.getUint16(offset + 32, true);
    const local = view.getUint32(offset + 42, true);
    if (next > directoryEnd || local + 30 > bytes.length || view.getUint32(local, true) !== 0x04034b50) invalid();
    if (flags & 1 || method !== 0) throw new Error('ZIP này dùng mã hóa hoặc nén chưa hỗ trợ xem trực tiếp. Vui lòng tải tệp để xem.');
    const start = local + 30 + view.getUint16(local + 26, true) + view.getUint16(local + 28, true);
    if (start + size > view.getUint32(end + 16, true) || size !== view.getUint32(offset + 24, true)) invalid();
    const entryName = new TextDecoder().decode(bytes.subarray(offset + 46, offset + 46 + nameLength));
    if (!entryName.endsWith('/')) files.push({ name: entryName, blob: new Blob([bytes.subarray(start, start + size)], { type: mimeTypes[entryName.split('.').pop().toLowerCase()] || 'application/octet-stream' }) });
    offset = next;
  }
  if (offset !== directoryEnd || !files.length) invalid();
  return files;
}
