tailwind.config = {
      darkMode: "class",
      theme: {
        extend: {
          "colors": {
            "secondary-container": "#fccc38",
            "surface-container-lowest": "#ffffff",
            "surface-bright": "#f8f9ff",
            "on-primary": "#ffffff",
            "secondary-fixed-dim": "#f0c12c",
            "tertiary-fixed": "#95f8a7",
            "primary-fixed-dim": "#ffb4ab",
            "surface-container": "#e6eeff",
            "on-surface": "#121c2a",
            "outline-variant": "#e4beb9",
            "background": "#f8f9ff",
            "primary-fixed": "#ffdad6",
            "on-tertiary-fixed": "#00210a",
            "primary-container": "#b91c1c",
            "tertiary-fixed-dim": "#79db8d",
            "surface-variant": "#d9e3f6",
            "surface-container-high": "#dee9fc",
            "tertiary": "#005223",
            "on-secondary": "#ffffff",
            "inverse-surface": "#27313f",
            "on-surface-variant": "#5b403d",
            "secondary-fixed": "#ffdf90",
            "inverse-primary": "#ffb4ab",
            "surface-dim": "#d0dbed",
            "on-tertiary-container": "#8bed9d",
            "on-secondary-container": "#6f5600",
            "on-tertiary": "#ffffff",
            "surface": "#f8f9ff",
            "on-primary-fixed-variant": "#93000b",
            "on-primary-fixed": "#410002",
            "on-tertiary-fixed-variant": "#005323",
            "error-container": "#ffdad6",
            "on-error": "#ffffff",
            "tertiary-container": "#006d30",
            "on-secondary-fixed-variant": "#584400",
            "on-error-container": "#93000a",
            "primary": "#93000b",
            "error": "#ba1a1a",
            "on-background": "#121c2a",
            "outline": "#8f6f6c",
            "surface-container-highest": "#d9e3f6",
            "on-secondary-fixed": "#241a00",
            "inverse-on-surface": "#eaf1ff",
            "secondary": "#755b00",
            "surface-tint": "#b91c1c",
            "on-primary-container": "#ffcdc7",
            "surface-container-low": "#eff4ff"
          },
          "borderRadius": {
            "DEFAULT": "0.25rem",
            "lg": "0.5rem",
            "xl": "0.75rem",
            "full": "9999px"
          },
          "spacing": {
            "space-xs": "0.25rem",
            "gutter": "1.5rem",
            "margin": "1.5rem",
            "space-sm": "0.5rem",
            "space-md": "1rem",
            "space-lg": "1.5rem",
            "space-xl": "2rem"
          },
          "fontFamily": {
            "body-md-medium": ["Be Vietnam Pro"],
            "body-md": ["Be Vietnam Pro"],
            "headline-md": ["Be Vietnam Pro"],
            "headline-lg-mobile": ["Be Vietnam Pro"],
            "headline-sm": ["Be Vietnam Pro"],
            "body-sm": ["Be Vietnam Pro"],
            "label-sm": ["Be Vietnam Pro"],
            "headline-lg": ["Be Vietnam Pro"],
            "display-lg": ["Be Vietnam Pro"],
            "display-lg-mobile": ["Be Vietnam Pro"],
            "body-lg": ["Be Vietnam Pro"],
            "label-md": ["Be Vietnam Pro"]
          },
          "fontSize": {
            "body-md-medium": ["14px", { "lineHeight": "24px", "fontWeight": "500" }],
            "body-md": ["14px", { "lineHeight": "24px", "fontWeight": "400" }],
            "headline-md": ["22px", { "lineHeight": "30px", "fontWeight": "600" }],
            "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
            "headline-sm": ["18px", { "lineHeight": "26px", "fontWeight": "600" }],
            "body-sm": ["12px", { "lineHeight": "20px", "fontWeight": "400" }],
            "label-sm": ["11px", { "lineHeight": "16px", "letterSpacing": "0.04em", "fontWeight": "600" }],
            "headline-lg": ["30px", { "lineHeight": "38px", "fontWeight": "700" }],
            "display-lg": ["40px", { "lineHeight": "48px", "fontWeight": "700" }],
            "display-lg-mobile": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
            "body-lg": ["16px", { "lineHeight": "26px", "fontWeight": "400" }],
            "label-md": ["13px", { "lineHeight": "18px", "letterSpacing": "0.02em", "fontWeight": "600" }]
          }
        },
      },
    }