import React, { useState } from 'react';
import { Button } from '../components/Button.jsx';
import { Card } from '../components/Card.jsx';
import { Tabs } from '../components/Tabs.jsx';
import { navigate } from '../lib/navigation.js';

export function AuthAccessPage() {
  const [feedback, setFeedback] = useState('');
  const action = (message) => setFeedback(`${message} Đây là giao diện chuẩn bị cho API, chưa gửi dữ liệu.`);
  return <main className="min-h-screen bg-[#F8FAFC] p-5 flex items-center justify-center"><Card className="w-full max-w-xl p-6 md:p-8"><a href="login.html" onClick={(event) => { event.preventDefault(); navigate('login.html'); }} className="text-body-sm font-semibold text-primary">← Về đăng nhập</a><h1 className="mt-4 text-headline-md font-bold">Tài khoản và khôi phục truy cập</h1><p className="mt-2 text-body-md text-[#64748B]">Các biểu mẫu tương ứng với đăng ký, quên mật khẩu và đặt lại mật khẩu của hệ thống.</p><div className="mt-6"><Tabs items={[{ id: 'SIGNUP', label: 'Đăng ký sinh viên' }, { id: 'FORGOT', label: 'Quên mật khẩu' }, { id: 'RESET', label: 'Đặt lại mật khẩu' }]}>{(tab) => <form className="pt-5 space-y-4" onSubmit={(event) => { event.preventDefault(); action(tab === 'SIGNUP' ? 'Đã tiếp nhận yêu cầu đăng ký.' : tab === 'FORGOT' ? 'Đã tiếp nhận yêu cầu gửi mã đặt lại.' : 'Đã tiếp nhận yêu cầu đặt lại mật khẩu.'); }}><label className="block text-body-sm font-semibold">{tab === 'RESET' ? 'Mã xác thực' : tab === 'SIGNUP' ? 'Tên đăng nhập' : 'Email'}<input required className="mt-2 h-11 w-full rounded-xl border border-[#CBD5E1] px-3" /></label>{tab === 'SIGNUP' && <label className="block text-body-sm font-semibold">Email<input required type="email" className="mt-2 h-11 w-full rounded-xl border border-[#CBD5E1] px-3" /></label>}{tab !== 'FORGOT' && <label className="block text-body-sm font-semibold">Mật khẩu mới<input required type="password" className="mt-2 h-11 w-full rounded-xl border border-[#CBD5E1] px-3" /></label>}<Button type="submit">{tab === 'SIGNUP' ? 'Tạo tài khoản' : tab === 'FORGOT' ? 'Gửi mã qua email' : 'Đặt lại mật khẩu'}</Button></form>}</Tabs></div>{feedback && <p className="mt-5 rounded-xl border border-[#86EFAC] bg-[#F0FDF4] px-4 py-3 text-body-sm text-[#15803D]">{feedback}</p>}</Card></main>;
}
