import React from 'react';
import { AppShell } from '../components/AppShell.jsx';
import { Card } from '../components/Card.jsx';
import { MetricGrid } from '../components/MetricGrid.jsx';
import { PageContainer } from '../components/PageContainer.jsx';
import { PageTitle } from '../components/PageTitle.jsx';
import { ProgressBar } from '../components/ProgressBar.jsx';
import { results } from '../data/lmsData.js';

export function LearningResultsPage() {
  const metrics = results.map((item) => ({ label: item.label, value: item.value, detail: item.unit, icon: item.icon, tone: item.tone === 'gold' ? 'warning' : item.tone }));
  return <AppShell currentPage="learning_results.html" title="Kết quả học tập · PTIT Physics 1" breadcrumbs={['Kết quả học tập']} current="Phân tích năng lực"><PageContainer><PageTitle eyebrow="DỮ LIỆU HỌC TẬP" title="Kết quả & phân tích năng lực" description="Theo dõi tiến bộ, điểm mạnh và các chủ đề cần cải thiện trong học kỳ này." /><MetricGrid items={metrics} /><div className="grid grid-cols-1 lg:grid-cols-2 gap-6"><Card className="p-6"><div className="flex items-center justify-between"><h2 className="text-headline-md font-bold">Tiến độ theo chương</h2><span className="text-body-sm text-[#64748B]">Học kỳ 1</span></div><div className="space-y-5 mt-6">{[['Động học chất điểm',100,'#15803D'],['Động lực học chất điểm',75,'#B91C1C'],['Công và năng lượng',42,'#B45309'],['Dao động và sóng',18,'#64748B']].map(([label,value,color]) => <div key={label}><div className="flex items-center justify-between text-body-md mb-2"><span>{label}</span><strong style={{color}}>{value}%</strong></div><div className="h-3 bg-[#E2E8F0] rounded-full overflow-hidden"><div className="h-full rounded-full" style={{width:`${value}%`,backgroundColor:color}} /></div></div>)}</div></Card><Card className="p-6"><div className="flex items-center justify-between"><h2 className="text-headline-md font-bold">Điểm theo tuần</h2><select className="rounded-lg border border-[#CBD5E1] px-3 py-2 text-body-sm bg-white"><option>8 tuần gần nhất</option><option>Cả học kỳ</option></select></div><div className="h-56 mt-6 flex items-end gap-3 border-b border-l border-[#E2E8F0] px-4 pb-0">{[55,68,62,76,72,84,79,88].map((value,index) => <div key={index} className="flex-1 flex flex-col items-center justify-end gap-2"><span className="text-label-sm text-[#64748B]">{value}%</span><div className="w-full rounded-t-lg bg-primary-container/80 hover:bg-primary-container transition-colors" style={{height:`${value*1.55}px`}} /><span className="text-label-sm text-[#94A3B8]">T{index+1}</span></div>)}</div></Card></div><Card className="p-6"><h2 className="text-headline-md font-bold">Gợi ý cải thiện cá nhân</h2><div className="grid grid-cols-1 md:grid-cols-3 gap-4 mt-5">{[['priority_high','Ôn lại lực ma sát','Bạn sai 3/5 câu ở chủ đề này. Làm bộ luyện tập Chương 2.','primary'],['auto_awesome','Phát huy điểm mạnh','Bạn có điểm cao ổn định ở chủ đề Động học.','success'],['schedule','Duy trì nhịp học','Học 25 phút mỗi ngày để giữ chuỗi 5 ngày.','warning']].map(([icon,title,text,tone]) => <div key={title} className={`p-4 rounded-xl border ${tone === 'primary' ? 'bg-[#FEF2F2] border-[#FECACA]' : tone === 'success' ? 'bg-[#F0FDF4] border-[#86EFAC]' : 'bg-[#FFFBEB] border-[#FDE68A]'}`}><span className="material-symbols-outlined text-primary">{icon}</span><h3 className="font-semibold mt-3">{title}</h3><p className="text-body-sm text-[#64748B] mt-1">{text}</p></div>)}</div></Card></PageContainer></AppShell>;
}
