import React, { useState } from 'react';
import { AppShell } from '../components/AppShell.jsx';
import { Button } from '../components/Button.jsx';
import { Card } from '../components/Card.jsx';
import { PageContainer } from '../components/PageContainer.jsx';
import { PageTitle } from '../components/PageTitle.jsx';
import { ProgressBar } from '../components/ProgressBar.jsx';
import { StatusBadge } from '../components/StatusBadge.jsx';
import { labs } from '../data/lmsData.js';

export function VirtualLabPage() {
  const [active, setActive] = useState(null);
  return <AppShell currentPage="virtual_lab.html" title="Phòng thí nghiệm 3D · PTIT Physics 1" breadcrumbs={['Phòng thí nghiệm 3D']} current="Danh sách thí nghiệm"><PageContainer><PageTitle eyebrow="MÔ PHỎNG TƯƠNG TÁC" title="Phòng thí nghiệm 3D" description="Thực hành các thí nghiệm vật lý trong môi trường mô phỏng an toàn, trực quan và có thể lặp lại." actions={<Button icon="history">Lịch sử thí nghiệm</Button>} /><Card className="p-6 bg-[#0F172A] text-white border-[#1E293B]"><div className="flex flex-col md:flex-row md:items-center justify-between gap-4"><div><StatusBadge tone="primary" className="bg-[#7F1D1D] text-[#FECACA] border-[#991B1B]">LAB ONLINE</StatusBadge><h2 className="text-headline-md font-bold mt-3">Không gian thực hành vật lý số</h2><p className="text-body-sm text-slate-300 mt-1">Chọn một thí nghiệm để bắt đầu thu thập dữ liệu và viết báo cáo.</p></div><a href="3d_workspace.html" className="inline-flex items-center justify-center gap-2 h-11 px-5 rounded-xl bg-primary-container text-white font-semibold hover:bg-[#991B1B]"><span className="material-symbols-outlined">open_in_new</span>Mở workspace</a></div></Card><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">{labs.map((lab) => <Card key={lab.title} className="overflow-hidden hover:-translate-y-1 hover:shadow-md transition-all"><div className={`h-36 bg-gradient-to-br ${lab.image === 'incline' ? 'from-[#7F1D1D] to-[#F59E0B]' : lab.image === 'collision' ? 'from-[#1E3A8A] to-[#0F766E]' : lab.image === 'pendulum' ? 'from-[#334155] to-[#7C3AED]' : 'from-[#14532D] to-[#0F766E]'} flex items-center justify-center text-white`}><span className="material-symbols-outlined text-6xl opacity-70">science</span></div><div className="p-5"><div className="flex items-center justify-between"><span className="text-label-md text-[#64748B]">{lab.code}</span><StatusBadge tone={lab.progress === 100 ? 'success' : lab.progress ? 'primary' : 'neutral'}>{lab.status}</StatusBadge></div><h2 className="text-headline-sm font-bold mt-3 min-h-[52px]">{lab.title}</h2><ProgressBar value={lab.progress} className="mt-4" /><div className="flex gap-2 mt-5"><Button className="flex-1" onClick={() => setActive(lab.title)} icon={lab.progress ? 'play_arrow' : 'lock_open'}>{lab.progress ? 'Tiếp tục' : 'Bắt đầu'}</Button><a href="lab_report_rubric.html"><button className="h-10 w-10 rounded-xl border border-[#CBD5E1] text-[#64748B] hover:text-primary hover:border-primary" aria-label="Xem báo cáo"><span className="material-symbols-outlined">description</span></button></a></div></div></Card>)}</div>{active && <Card className="p-5 border-primary/30 bg-[#FEF2F2]"><div className="flex items-center justify-between"><div><strong className="text-body-md">Đã chọn: {active}</strong><p className="text-body-sm text-[#64748B] mt-1">Workspace mô phỏng sẵn sàng để bạn tiếp tục.</p></div><a href="3d_workspace.html" className="text-body-sm text-primary font-semibold">Mở ngay →</a></div></Card>}</PageContainer></AppShell>;
}
